version: "3.7"

services:
  mysql:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      TZ: Asia/Seoul
    env_file:
      - ./db.env
    volumes:
      - /home/ec2-user/db/data:/var/lib/mysql
      - /home/ec2-user/db/conf.d:/etc/mysql/conf.d
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
    networks:
      - wedding-network
    container_name: wedding-mysql

  backend:
    image: backend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8081:8081
    networks:
      - wedding-network
    container_name: wedding-backend
#    depends_on:
#      - mysql

  frontend:
    image: frontend
    build:
      context: .
      dockerfile: ./Dockerfile-prod
    ports:
      - 5173:5173
    networks:
      - wedding-network
    container_name: wedding-fronend
#    depends_on:
#      - backend

networks:
  wedding-network: